---
name: Docs

"on":
  push:
    branches:
      - main

jobs:
  docs:
    strategy:
      matrix:
        dc:
          - dmd-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: 'Build'
        run: |
          dub build -b ddox
          touch docs/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
